## Fancy Indexing

In [1]:
import numpy as np

In [4]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[-1]

10

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [14]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

In [15]:
arr[2::2]

array([ 2,  4,  6,  8, 10])

## Broadcasting

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr[:5]=77
arr

array([77, 77, 77, 77, 77,  5,  6,  7,  8,  9, 10])

In [22]:
arr

array([77, 77, 77, 77, 77,  5,  6,  7,  8,  9, 10])

In [23]:
a=[0,2,4,6,8,10]

In [25]:
a[0:3] = [100,100,100]
a

[100, 100, 100, 6, 8, 10]

In [26]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
slice_of_arr=arr[:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [29]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [30]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [32]:
arr_copy=arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [34]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [35]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

In [38]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
arr_2d[0:1]

array([[ 5, 10, 15]])

In [40]:
arr_2d[:1]

array([[ 5, 10, 15]])

In [41]:
arr_2d[-3]

array([ 5, 10, 15])

In [42]:
arr_2d[1]

array([20, 25, 30])

In [43]:
arr_2d[1][2]

30

In [44]:
arr_2d[1,2]

30

In [45]:
arr_2d[2,1]

40

In [47]:
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [48]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
arr_2d[2:,:]

array([[35, 40, 45]])

In [51]:
arr_2d[2:,0:3]

array([[35, 40, 45]])

In [53]:
arr_2d[:,1:2]

array([[10],
       [25],
       [40]])

In [54]:
arr_2d[:,2:]

array([[15],
       [30],
       [45]])

In [55]:
arr_2d[1,1]=99
arr_2d

array([[ 5, 10, 15],
       [20, 99, 30],
       [35, 40, 45]])

In [56]:
arr_2d[1,1]=7.7
arr_2d

array([[ 5, 10, 15],
       [20,  7, 30],
       [35, 40, 45]])

## Fancy Indexing

In [58]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [59]:
v[1]

3

In [60]:
v[3]

9

In [61]:
v[7]

21

In [66]:
v[[1,3,7]]

array([ 3,  9, 21])

In [67]:
v[[1,3,5]]

array([ 3,  9, 15])

In [68]:
arr2d = np.zeros((10,10), dtype = int)
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [69]:
arr2d.shape

(10, 10)

In [71]:
arr2d.shape[1]

10

In [73]:
arr2d[3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [74]:
arr2d[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
for i in range(10):
    arr2d[i]=i
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [76]:
arr2d[[2,4,6,8]]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [77]:
arr2d[[6,4,2,7]]

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [78]:
arr_2d = np.array ([[5,10,15],[20,25,30],[35,40,45]])
for i in arr_2d:
    print (list(filter(lambda x : x%2 , i)))

[5, 15]
[25]
[35, 45]


In [85]:
arr_2d = np.array ([[5,10,15],[20,25,30],[35,40,45]])
[(list(filter(lambda x : x%2 , i))) for i in arr_2d]

[[5, 15], [25], [35, 45]]

## any_arr[[row], [column]]

In [86]:
jj = np.arange(1,17).reshape(4,4)
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [87]:
jj[[1, 2], [0, 3]]

array([ 5, 12])

In [88]:
jj[[0, 2, 3], [0, 1,  3]]

array([ 1, 10, 16])

In [89]:
jj[1, [1, 3]]

array([6, 8])

In [90]:
jj[[0, 3], 1]

array([ 2, 14])

In [91]:
jj[:, [1, 2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [93]:
jj[1:3, [1,2]]

array([[ 6,  7],
       [10, 11]])

## More Indexing Help
## Selection

In [95]:
arr = np.arange(1,11)

In [96]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [97]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [98]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [99]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [100]:
arr != 3

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

In [101]:
arr[arr != 3]

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr[(arr != 3) & (arr != 4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

## Arithmetic Operations

In [103]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [105]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [106]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [107]:
v * 5 / 10 -1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

## Universal Array Functions

In [108]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [110]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [111]:
np.exp(1)

2.718281828459045

In [112]:
2.718281828459045 ** 2

7.3890560989306495

In [113]:
np.exp(2)

7.38905609893065

In [114]:
np.max(arr)

9

In [115]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [116]:
np.sin(np.pi/2)

1.0

In [117]:
np.tan(np.pi/4)

0.9999999999999999

In [118]:
np.log10(1000)

3.0

In [119]:
v

array([1, 2, 3, 4, 5])

In [120]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [121]:
x1 = np.arange(9.0).reshape(3,3)
x2 = np.arange(3.0)
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [122]:
x2

array([0., 1., 2.])

In [123]:
np.subtract(x1,x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [124]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [125]:
np.multiply(v, 5)

array([ 5, 10, 15, 20, 25])

In [126]:
np.divide(v, 2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [127]:
np.power(v, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [128]:
v ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [129]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [130]:
v%2

array([1, 0, 1, 0, 1], dtype=int32)