In [3]:
import numpy as np

In [9]:
mylist=[1,2,3]

In [10]:
type(mylist)

list

In [11]:
np.array(mylist)

array([1, 2, 3])

In [12]:
mylist

[1, 2, 3]

In [13]:
myarr = np.array(my_list)

In [14]:
myarr

array([1, 2, 3])

In [15]:
type(myarr)

numpy.ndarray

In [18]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [30]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [32]:
len(np.linspace(0,5,21))

21

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.random.rand(1)

array([0.07145044])

In [35]:
np.random.rand(5,6)

array([[0.83805452, 0.20285185, 0.64662392, 0.1376937 , 0.59521591,
        0.73345973],
       [0.43453758, 0.13784797, 0.53033855, 0.4498829 , 0.79244901,
        0.90432196],
       [0.14278581, 0.78728697, 0.82629993, 0.60318602, 0.13547015,
        0.2047732 ],
       [0.23189994, 0.48764014, 0.62216412, 0.72481592, 0.97598584,
        0.03364871],
       [0.4385854 , 0.46233107, 0.9818182 , 0.47257329, 0.29257043,
        0.94755446]])

In [36]:
np.random.rand(5,2)

array([[0.07865348, 0.50453364],
       [0.7377399 , 0.12684867],
       [0.36211847, 0.85139605],
       [0.71669026, 0.27302583],
       [0.8046911 , 0.83905438]])

In [37]:
np.random.randn(10)

array([ 0.13935221, -0.11621726,  0.46222141,  1.51933656, -1.56288319,
       -1.13904184,  0.3568726 , -0.58686863,  1.11885826,  0.07966793])

In [38]:
np.random.randn(2,3)

array([[ 1.15691157, -0.45115955,  1.17558216],
       [-0.75355116,  0.55227501, -1.51004628]])

In [39]:
np.random.randint(0,101,5)

array([86, 80, 29,  8, 54])

In [40]:
np.random.randint(0,101,(4,5))

array([[37,  5, 70, 79, 88],
       [15, 79, 78, 59,  9],
       [56,  1, 40,  2, 88],
       [38, 93, 22,  7, 93]])

In [42]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [43]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [44]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [45]:
np.random.rand(4)

array([0.60111501, 0.70807258, 0.02058449, 0.96990985])

In [46]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [47]:
arr = np.arange(0,25)

In [48]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [56]:
ranarr = np.random.randint(0,101,10)
ranarr

array([57, 21, 88, 48, 90, 58, 41, 91, 59, 79])

In [57]:
ranarr.max()

91

In [58]:
ranarr.min()

21

In [59]:
ranarr.argmax()

7

In [60]:
ranarr.argmin()

1

In [61]:
ranarr.dtype

dtype('int32')

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [63]:
arr.shape

(25,)

In [69]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
arr.shape

(5, 5)

In [71]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [72]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

numpy.org