In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr[:] = 99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [17]:
arr_copy = arr.copy()

In [19]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [20]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [23]:
arr_2d = np.array([[5,10,15],[20,25,30],[25,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [25, 40, 45]])

In [24]:
arr_2d[0]

array([ 5, 10, 15])

In [25]:
arr_2d.shape

(3, 3)

In [26]:
arr_2d[2]

array([25, 40, 45])

In [27]:
arr_2d[1][1]

25

In [28]:
arr_2d[(1,1)]

25

In [29]:
arr_2d[1,1]

25

In [30]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [31]:
arr_2d[:2,1]

array([10, 25])

In [32]:
arr_2d[1:2,1:2]

array([[25]])

In [34]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [36]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [37]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
newarr = arr[arr>4]
newarr

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])